# Generated by Django 6.0.5 on 2026-05-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Self Help', 'Self Help'), ('Fiction', 'Fiction'), ('Religious', 'Religious'), ('Science', 'Science'), ('Other', 'Other')], max_length=100),
        ),
    ]
